name: Make

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libmariadb-dev \
            libmariadb-dev-compat \
            liblua5.3-dev \
            libdb5.3-dev \
            libssl-dev \
            cmake \
            git \
            default-jre \
            libboost-all-dev \
            gdb \
            ninja-build \
            libjemalloc-dev \
            lua5.3 \
            luarocks
      - name: Install Lua test dependencies
        run: sudo luarocks install busted
      - name: Run make build-ninja-debug
        run: make build-ninja-debug
        working-directory: MMOCoreORB
      - name: Run unit tests
        run: ctest --test-dir MMOCoreORB/build/unix/ninja-debug -R core3 --output-on-failure --verbose
      - name: Run Lua tests
        run: LUA_PATH=MMOCoreORB/bin/scripts/?.lua;; busted --verbose spec
